
CREATE TABLE EPS (
    ID_EPS          NUMBER(10)      NOT NULL,
    NOMBRE_EPS      VARCHAR2(120)   NOT NULL,
    DIRECCION_EPS   VARCHAR2(150),
    CONSTRAINT PK_EPS PRIMARY KEY (ID_EPS)
);


CREATE TABLE IPS (
    ID_IPS          NUMBER(10)      NOT NULL,
    NOMBRE_IPS      VARCHAR2(120)   NOT NULL,
    DIRECCION_IPS   VARCHAR2(150),
    ID_EPS          NUMBER(10),
    CONSTRAINT PK_IPS PRIMARY KEY (ID_IPS),
    CONSTRAINT FK_IPS_EPS
        FOREIGN KEY (ID_EPS)
        REFERENCES EPSANDES.EPS (ID_EPS)
        ON DELETE SET NULL
);


CREATE TABLE AFILIADO (
    ID_AFILIADO         NUMBER(10)      NOT NULL,
    NOMBRE_AFILIADO     VARCHAR2(120)   NOT NULL,
    FECHA_NACIMIENTO    DATE            NOT NULL,
    TIPO_AFILIACION     VARCHAR2(30)
        CONSTRAINT CHK_TIPO_AFILIACION
            CHECK (TIPO_AFILIACION IN ('Contributivo','Beneficiario')),
  
    CONSTRAINT PK_AFILIADO PRIMARY KEY (ID_AFILIADO)
);


CREATE TABLE ENFERMEDAD (
    ID_ENFERMEDAD    NUMBER(10)      NOT NULL,
    NOMBRE_ENFERMEDAD VARCHAR2(100)  NOT NULL,
    DESCRIPCION      VARCHAR2(4000),
    SINTOMAS         VARCHAR2(4000),
    CONSTRAINT PK_ENFERMEDAD PRIMARY KEY (ID_ENFERMEDAD)
);


CREATE TABLE AFILIADO_ENFERMEDAD (
    ID_AFILIADO       NUMBER(10) NOT NULL,
    ID_ENFERMEDAD     NUMBER(10) NOT NULL,
    
    FECHA_DIAGNOSTICO DATE,
    CONSTRAINT PK_AFILIADO_ENFERMEDAD
        PRIMARY KEY (ID_AFILIADO, ID_ENFERMEDAD),
    CONSTRAINT FK_AE_AFILIADO
        FOREIGN KEY (ID_AFILIADO)
        REFERENCES EPSANDES.AFILIADO (ID_AFILIADO)
        ON DELETE CASCADE,
    CONSTRAINT FK_AE_ENFERMEDAD
        FOREIGN KEY (ID_ENFERMEDAD)
        REFERENCES EPSANDES.ENFERMEDAD (ID_ENFERMEDAD)
        ON DELETE CASCADE
);


CREATE TABLE ESPECIALIDAD (
    ID_ESPECIALIDAD      NUMBER(10)     NOT NULL,
    NOMBRE_ESPECIALIDAD  VARCHAR2(100)  NOT NULL,
    CONSTRAINT PK_ESPECIALIDAD
        PRIMARY KEY (ID_ESPECIALIDAD)
);


CREATE TABLE MEDICO (
    ID_MEDICO         NUMBER(10)      NOT NULL,
    NOMBRE_MEDICO     VARCHAR2(120)   NOT NULL,
    REGISTRO_MEDICO   VARCHAR2(50)    NOT NULL,
    ID_ESPECIALIDAD   NUMBER(10),  
    CONSTRAINT PK_MEDICO PRIMARY KEY (ID_MEDICO),
    CONSTRAINT UQ_MEDICO_REGISTRO UNIQUE (REGISTRO_MEDICO),
    CONSTRAINT FK_MEDICO_ESP
        FOREIGN KEY (ID_ESPECIALIDAD)
        REFERENCES EPSANDES.ESPECIALIDAD (ID_ESPECIALIDAD)
);


CREATE TABLE SERVICIO_SALUD (
    ID_SERVICIO       NUMBER(10)       NOT NULL,
    DESCRIPCION       VARCHAR2(200)    NOT NULL,

    CONSTRAINT PK_SERVICIO_SALUD
        PRIMARY KEY (ID_SERVICIO)
);


CREATE TABLE IPS_SERVICIO (
    ID_IPS        NUMBER(10)  NOT NULL,
    ID_SERVICIO   NUMBER(10)  NOT NULL,
   
    CONSTRAINT PK_IPS_SERVICIO
        PRIMARY KEY (ID_IPS, ID_SERVICIO),
    CONSTRAINT FK_IS_IPS
        FOREIGN KEY (ID_IPS)
        REFERENCES EPSANDES.IPS (ID_IPS)
        ON DELETE CASCADE,
    CONSTRAINT FK_IS_SERVICIO
        FOREIGN KEY (ID_SERVICIO)
        REFERENCES EPSANDES.SERVICIO_SALUD (ID_SERVICIO)
        ON DELETE CASCADE
);


CREATE TABLE ORDEN_BASE (
    ID_ORDEN       NUMBER(10)  NOT NULL,
    FECHA_EMISION  DATE        NOT NULL,
    ID_AFILIADO    NUMBER(10)  NOT NULL,
    ID_MEDICO      NUMBER(10)  NOT NULL,
    ID_SERVICIO    NUMBER(10)  NOT NULL,
    CONSTRAINT PK_ORDEN_BASE
        PRIMARY KEY (ID_ORDEN),
    CONSTRAINT FK_OB_AFILIADO
        FOREIGN KEY (ID_AFILIADO)
        REFERENCES EPSANDES.AFILIADO (ID_AFILIADO),
    CONSTRAINT FK_OB_MEDICO
        FOREIGN KEY (ID_MEDICO)
        REFERENCES EPSANDES.MEDICO (ID_MEDICO),
    CONSTRAINT FK_OB_SERVICIO
        FOREIGN KEY (ID_SERVICIO)
        REFERENCES EPSANDES.SERVICIO_SALUD (ID_SERVICIO)
);


CREATE TABLE ESTADO_ORDEN (
    ID_ORDEN    NUMBER(10)     NOT NULL,
    ESTADO      VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_ESTADO_ORDEN
        PRIMARY KEY (ID_ORDEN),
    CONSTRAINT FK_EO_ORDEN
        FOREIGN KEY (ID_ORDEN)
        REFERENCES EPSANDES.ORDEN_BASE (ID_ORDEN)
        ON DELETE CASCADE
);


CREATE TABLE CITA_BASE (
    ID_CITA        NUMBER(10)   NOT NULL,
    FECHA_CITA     DATE         NOT NULL,
    HORA_CITA      VARCHAR2(8),  
    ID_AFILIADO    NUMBER(10)   NOT NULL,
    ID_MEDICO      NUMBER(10)   NOT NULL,
    ID_IPS         NUMBER(10)   NOT NULL,
    ID_SERVICIO    NUMBER(10),
    CONSTRAINT PK_CITA_BASE
        PRIMARY KEY (ID_CITA),
    CONSTRAINT FK_CB_AFILIADO
        FOREIGN KEY (ID_AFILIADO)
        REFERENCES EPSANDES.AFILIADO (ID_AFILIADO),
    CONSTRAINT FK_CB_MEDICO
        FOREIGN KEY (ID_MEDICO)
        REFERENCES EPSANDES.MEDICO (ID_MEDICO),
    CONSTRAINT FK_CB_IPS
        FOREIGN KEY (ID_IPS)
        REFERENCES EPSANDES.IPS (ID_IPS),
    CONSTRAINT FK_CB_SERV
        FOREIGN KEY (ID_SERVICIO)
        REFERENCES EPSANDES.SERVICIO_SALUD (ID_SERVICIO)
);


CREATE TABLE ESTADO_CITA (
    ID_CITA    NUMBER(10)    NOT NULL,
    ESTADO     VARCHAR2(50)  NOT NULL,
    CONSTRAINT PK_ESTADO_CITA
        PRIMARY KEY (ID_CITA),
    CONSTRAINT FK_EC_CITA
        FOREIGN KEY (ID_CITA)
        REFERENCES EPSANDES.CITA_BASE (ID_CITA)
        ON DELETE CASCADE
);


CREATE TABLE ATENCION_MEDICA (
    ID_ATENCION     NUMBER(10)    NOT NULL,
    ID_CITA         NUMBER(10)    NOT NULL,
    DIAGNOSTICO     VARCHAR2(4000),
    RESULTADOS      VARCHAR2(4000),
    CONSTRAINT PK_ATENCION_MEDICA
        PRIMARY KEY (ID_ATENCION),
    CONSTRAINT FK_AM_CITA
        FOREIGN KEY (ID_CITA)
        REFERENCES EPSANDES.CITA_BASE (ID_CITA)
        ON DELETE CASCADE
);

CREATE TABLE AGENDA(
ID_IPS_MEDICO NUMBER(10) NOT NULL,
FECHA_HORA DATE NOT NULL, 
ESTADO VARCHAR2(10) NOT NULL,
CONSTRAINT PK_AGENDA PRIMARY KEY (ID_IPS_MEDICO, FECHA_HORA)
);

CREATE TABLE ESPECIALIDAD_SERVICIO(
ID_ESPECIALIDAD NUMBER(10) NOT NULL,
ID_SERVICIO NUMBER(10) NOT NULL, 
CONSTRAINT PK_ESPECIALIDAD_SERVICIO PRIMARY KEY (ID_ESPECIALIDAD, ID_SERVICIO)
);

CREATE TABLE IPS_MEDICO(
ID_IPS_MEDICO NUMBER(10) NOT NULL,
ID_IPS NUMBER(10) NOT NULL,
ID_EPS NUMBER(10) NOT NULL,
ID_MEDICO NUMBER(10) NOT NULL,
ID_SERVICIO NUMBER(10) NOT NULL,
CONSTRAINT PK_IPS_MEDICO PRIMARY KEY (ID_IPS, ID_EPS, ID_MEDICO, ID_SERVICIO)
);

INSERT INTO IPS (ID_IPS, NOMBRE_IPS, DIRECCION_IPS, ID_EPS) 
VALUES (1, 'Clínica', 'Calle 60 #5-30', NULL);  

INSERT INTO IPS (ID_IPS, NOMBRE_IPS, DIRECCION_IPS, ID_EPS) 
VALUES (1, 'Hospital Norte', 'Calle 24 #7-40', NULL);

INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE_ESPECIALIDAD) 
VALUES (1, 'Cardiología');

INSERT INTO MEDICO (ID_MEDICO, NOMBRE_MEDICO, REGISTRO_MEDICO, ID_ESPECIALIDAD) 
VALUES (1, 'Juan', 'MED-1234', 1);

INSERT INTO MEDICO (ID_MEDICO, NOMBRE_MEDICO, REGISTRO_MEDICO, ID_ESPECIALIDAD) 
VALUES (2, 'Diana', 'MED-5678', 5);

INSERT INTO AFILIADO (ID_AFILIADO, NOMBRE_AFILIADO, FECHA_NACIMIENTO, TIPO_AFILIACION) 
VALUES (1, 'Andres Perez', DATE '2003-05-10', 'Contributivo');

INSERT INTO AFILIADO (ID_AFILIADO, NOMBRE_AFILIADO, FECHA_NACIMIENTO, TIPO_AFILIACION) 
VALUES (2, 'Pedrito', DATE '2028-09-20', 'Contributivo');

INSERT INTO IPS (ID_IPS, NOMBRE_IPS, DIRECCION_IPS, ID_EPS) 
VALUES (3, 'Centro Médico 1', 'Calle 60a #10-20', NULL);

INSERT INTO SERVICIO_SALUD (ID_SERVICIO, DESCRIPCION) 
VALUES (1, 'Consulta médica básica');

INSERT INTO IPS_SERVICIO (ID_IPS, ID_SERVICIO) VALUES (3, 1);

INSERT INTO MEDICO (ID_MEDICO, NOMBRE_MEDICO, REGISTRO_MEDICO, ID_ESPECIALIDAD) 
VALUES (3, 'Camilo Sanchez', 'MED-1234', 1);

INSERT INTO AFILIADO (ID_AFILIADO, NOMBRE_AFILIADO, FECHA_NACIMIENTO, TIPO_AFILIACION) 
VALUES (3, 'Maria José', DATE '1990-03-22', 'Contributivo');

INSERT INTO ORDEN_BASE (ID_ORDEN, FECHA_EMISION, ID_AFILIADO, ID_MEDICO, ID_SERVICIO) 
VALUES (1, DATE '2025-03-01', 3, 3, 1);

INSERT INTO ESTADO_ORDEN (ID_ORDEN, ESTADO) VALUES (1, 'Vigente');

INSERT INTO CITA_BASE (ID_CITA, FECHA_CITA, HORA_CITA, ID_AFILIADO, ID_MEDICO, ID_IPS, ID_SERVICIO) 
VALUES (1, DATE '2025-03-10', '10:00', 3, 3, 3, 1);

INSERT INTO ESTADO_CITA (ID_CITA, ESTADO) VALUES (1, 'Agendada');

INSERT INTO ATENCION_MEDICA (ID_ATENCION, ID_CITA, DIAGNOSTICO, RESULTADOS) 
VALUES (1, 1, 'Resfriado', 'Recetado Paracetamol');












