--RFC1:
SELECT SERVICIO_SALUD.DESCRIPCION, TO_CHAR(AGENDA.FECHA_HORA, 'DD/MM/YY') AS FECHA, TO_CHAR(AGENDA.FECHA_HORA, 'HH24:MI') 
AS HORA, IPS.NOMBRE_IPS, MEDICO.NOMBRE_MEDICO
FROM IPS_MEDICO, AGENDA, SERVICIO_SALUD, IPS, MEDICO WHERE
IPS_MEDICO.ID_IPS_MEDICO = AGENDA.ID_IPS_MEDICO
AND IPS_MEDICO.ID_SERVICIO = SERVICIO_SALUD.ID_SERVICIO
AND IPS_MEDICO.ID_IPS = IPS.ID_IPS
AND IPS_MEDICO.ID_MEDICO = MEDICO.ID_MEDICO
AND SERVICIO_SALUD.ID_SERVICIO = 13
AND AGENDA.ESTADO = 'DISPONIBLE'
AND AGENDA.FECHA_HORA >= TO_DATE('01/03/2024', 'DD/MM/YYYY')
ORDER BY AGENDA.FECHA_HORA

