--RFC2:
SELECT ID_SERVICIO, COUNT(*) AS total_ordenes
FROM ORDEN_BASE 
WHERE FECHA_EMISION BETWEEN TO_DATE('02/03/2024', 'DD/MM/YYYY') AND TO_DATE('11/03/2024', 'DD/MM/YYYY')
GROUP BY id_servicio
ORDER BY total_ordenes DESC;

SELECT IPS_MEDICO.ID_IPS,IPS.NOMBRE_IPS,EPS.NOMBRE_EPS,MEDICO.NOMBRE_MEDICO, SERVICIO_SALUD.DESCRIPCION FROM IPS_MEDICO,IPS,EPS,MEDICO,SERVICIO_SALUD 
WHERE IPS_MEDICO.ID_IPS=IPS.ID_IPS AND 
IPS_MEDICO.ID_EPS=EPS.ID_EPS AND
IPS_MEDICO.ID_MEDICO= MEDICO.ID_MEDICO AND
IPS_MEDICO.ID_SERVICIO = SERVICIO_SALUD.ID_SERVICIO
AND IPS_MEDICO.ID_IPS =104
