--RFC3:
SELECT SS.ID_SERVICIO, SS.DESCRIPCION AS SERVICIO,
COUNT(CB.ID_CITA) AS SERVICIOS_USADOS,
(SELECT COUNT(*) FROM SERVICIO_SALUD) AS SERVICIOS_DISPONIBLES,
ROUND(COUNT(CB.ID_CITA) / (SELECT COUNT(*) FROM SERVICIO_SALUD), 2) AS INDICE_USO
FROM SERVICIO_SALUD SS
LEFT JOIN CITA_BASE CB ON SS.ID_SERVICIO = CB.ID_SERVICIO
AND CB.FECHA_CITA BETWEEN TO_DATE('01/03/2024', 'DD/MM/YYYY') AND TO_DATE('30/03/2024', 'DD/MM/YYYY')
GROUP BY SS.ID_SERVICIO, SS.DESCRIPCION
ORDER BY SS.ID_SERVICIO;
