--RFC4:

SELECT CITA_BASE.ID_AFILIADO, AFILIADO.NOMBRE_AFILIADO, CITA_BASE.FECHA_CITA, MEDICO.NOMBRE_MEDICO,IPS.NOMBRE_IPS,
COUNT(*) AS TOTAL_CITAS
FROM CITA_BASE, AFILIADO, MEDICO, IPS
WHERE CITA_BASE.ID_AFILIADO = AFILIADO.ID_AFILIADO
AND CITA_BASE.ID_MEDICO = MEDICO.ID_MEDICO
AND CITA_BASE.ID_IPS = IPS.ID_IPS
AND CITA_BASE.ID_AFILIADO = 2019
AND CITA_BASE.FECHA_CITA BETWEEN TO_DATE('01/03/2024','DD/MM/YYYY') AND TO_DATE('15/03/2024','DD/MM/YYYY')
GROUP BY CITA_BASE.ID_AFILIADO, AFILIADO.NOMBRE_AFILIADO, CITA_BASE.FECHA_CITA, MEDICO.NOMBRE_MEDICO, IPS.NOMBRE_IPS;
